name: CI

on: [pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v2

      - name: Go to website dir
        run: cd website/

      - name: Install Dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm types:check

      - name: Lint
        run: pnpm lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
